name: Amul Stock Checker

on:
  schedule:
    - cron: '*/10 * * * *'  # runs every 10 minutes
  workflow_dispatch:       # allow manual runs

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          rfbrowser init --skip-browser-download
          playwright install chromium

      - name: Run Robot Framework script
        run: robot amul.robot

      - name: Notify if available
        if: ${{ failure() == false }}  # we assume pass means available
        run: |
          echo "Product is available!" | mail -s "Amul Alert" ${{ secrets.NOTIFY_EMAIL }}
